- src/app/_component/common/BottomNav.tsx
- src/app/payment/page.tsx
- tailwind.config.ts
와이어프레임을 보고 결제페이지 초안 퍼블리싱을 하였습니다.
1월5일자로 갑자기 수정이 들어가는 바람에 해당PR 머지 후 재작업 들어가겠습니다.
+추가로 input type checkbox로 체크박스를 만들었는데 커스텀을 아직 못하였습니다. 참고부탁드립니다.
+상단 도형도 수정하겠습니다 ㅠㅠ 너무어렵네요
+아 메인페이지에 결제페이지버튼을 임시로 만들었습니다.(보고 작업하기위함)
<br/>
❌
❌
> Feat: 결제페이지 초안 퍼블리싱

- src/api/signin/postSignin.ts
- src/app/(non-navbar)/email-signin/_component/EmailSigninForm.tsx
- src/mocks/handlers.ts
- 로그인, 회원가입 부분 MSW API 추가했습니다.
- 테스트용으로 로그인 fetch함수 api에 추가하였습니다.
- 이후에 MSW설정을 수정할 예정입니다.
X
> Feat: 로그인, 회원가입 MSW API 추가 및 테스트 액션 추가

- src/app/(navbar)/my/_types/my.types.ts
- src/app/(navbar)/my/menu/_component/AuthItems.tsx
- src/app/(navbar)/my/menu/_component/List.tsx
- src/app/(navbar)/my/menu/_component/ListItem.tsx
- src/app/(navbar)/my/menu/faq/page.tsx
- src/app/(navbar)/my/menu/notice/page.tsx
- src/app/(navbar)/my/menu/page.tsx
- src/app/types.ts
> Move: 타입지정 경로 수정

- src/api/signin/postSignin.ts
- src/app/(non-navbar)/email-signin/_component/EmailSigninForm.tsx
- src/app/(non-navbar)/email-signin/_component/SigninInput.tsx
- src/utils/validateEmail.ts
- 이메일 정규식 검사 함수를 추가했습니다.
- 이메일 로그인 msw연결을 하였습니다.
- 로그인 응답에 409코드는 상태를 나눠서 확인해 보기 위한 임시 코드입니다.
X
> Feat: 이메일 로그인 추가

- src/app/(non-navbar)/email-signin/_component/EmailSigninForm.tsx
- src/app/(non-navbar)/email-signin/_component/TermsForm.tsx
- src/app/(non-navbar)/email-signup/_component/EmailAuth.tsx
- src/app/(non-navbar)/email-signup/_component/EnterPassword.tsx
- src/app/(non-navbar)/email-signup/_component/SignupComplete.tsx
- src/app/(non-navbar)/email-signup/page.tsx
- 약관 동의 안 하고 이메일 페이지 접근 시 약관 동의 화면으로 이동되도록 수정하였습니다.
- 에러메시지가 input 입력 중일 때 사라지도록 변경하였습니다.
X
X
> Refactor: 이메일 회원가입 접근 제한

- src/app/(non-navbar)/email-signin/_component/CertificationCount.tsx
- src/app/(non-navbar)/schedule/[id]/_component/Calender.tsx
- src/app/(non-navbar)/schedule/[id]/_component/CalenderDays.tsx
- src/app/(non-navbar)/schedule/[id]/_component/CalenderWeeks.tsx
- src/app/(non-navbar)/schedule/[id]/_component/SelectedProduct.tsx
- src/app/(non-navbar)/schedule/[id]/page.tsx
- src/app/types.ts
- src/mocks/data/packageScheduleData.ts
- src/utils/formatDigitNumber.ts
- src/utils/generateDays.ts
- 날짜 개별 데이터 항목 추가
- 날짜별 가격 데이터 연동 추가
- 버튼 비활성화 수정
모바일
웹
X
X
> Feat: 날짜별 가격 데이터 표시 추가

- src/app/(non-navbar)/schedule/[id]/_component/CalenderDays.tsx
- src/app/(non-navbar)/schedule/[id]/_component/SelectedProduct.tsx
- src/hooks/query/usePackageDetailQuery.ts
- src/hooks/query/useScheduleListQuery.ts
- 선택 상품의 이미지가 표시되도록 수정하였습니다.
- 리액트 쿼리 함수를 별도 파일로 분리하였습니다.
X
X
> Feat: 선택 상품 이미지 노출, 리액트 쿼리 파일 분리

- src/api/my/getMyInfo.ts
- src/api/my/getMyOrders.ts
- src/api/my/getMyReviews.ts
- src/api/my/getMyUpcomingPackage.ts
- src/app/(navbar)/my/_component/MyReviewTabContent.tsx
- src/app/(navbar)/my/_component/ReservationItem.tsx
- src/app/(navbar)/my/_component/ReservationTabContent.tsx
- src/app/(navbar)/my/_component/UpcomingPackages.tsx
- src/app/(navbar)/my/_component/UserInfo.tsx
- src/app/constants.ts
- src/app/types.ts
- src/hooks/query/useMyInfoQuery.tsx
- src/hooks/query/useMyOrdersQuery.tsx
- src/hooks/query/useMyReviewsQuery.tsx
- src/hooks/query/useMyUpcomingPackageQuery.tsx
- src/mocks/handlers.ts
- mock 데이터 추가
- 마이페이지 첫 화면 msw 데이터 연동(내 정보, 다가오는 패키지, 예약내역, 내 리뷰 목록)
- 마이페이지 관련 타입 추가
추가된 파일, 변경된 파일이 많은데 단순 msw 연동 작업만 했습니다!
> Feat: 마이페이지 첫 화면 msw 데이터 연동

- src/api/my/deleteMyReview.ts
- src/app/(navbar)/my/_component/MyReviewTabContent.tsx
- src/hooks/query/useDeleteReviewMutation.ts
- src/mocks/data/myReviewData.ts
- src/mocks/handlers.ts
- 리뷰 삭제 기능 구현
현재 x버튼 클릭 시 냅다 삭제되는데..
디스크립션에 삭제 아이콘 클릭 시 사용자 알림 / 변경되는 UI에 대한 설명이 누락되어있어 논의 후 추가 예정입니다!
> Feat: 리뷰 삭제 기능 구현

- src/api/my/deleteMyReview.ts
- src/api/my/getFaqList.ts
- src/api/my/getMyInfo.ts
- src/api/my/getMyOrders.ts
- src/api/my/getMyReviews.ts
- src/api/my/getMyUpcomingPackage.ts
- src/api/my/getNoticeList.ts
- api 요청에 credentials 추가 하였습니다.
-기존 에러 처리 try-catch문으로 변경하였습니다.
> Fix: api 요청에 credentials 추가 및 try-catch문으로 변경

- src/api/items/getPackageDetail.ts
- src/app/(non-navbar)/items/[id]/_component/ChangeDateButton.tsx
- src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
- src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
- src/app/(non-navbar)/items/[id]/_component/StorePerson.tsx
- src/app/(non-navbar)/items/[id]/page.tsx
- src/app/(non-navbar)/schedule/[id]/page.tsx
- src/hooks/query/usePackageDetailQuery.ts
- src/store/usePaymentStore.ts
- 출발일 변경 시 일정 선택 페이지에 적용 안되는 문제 해결
- 일정 선택하면 상세페이지 일정에 적용 안되는 문제 해결
- 주스텐드 인원 선택 함수 연결
- 결제 정보 저장
X
X
> Feat: 상세 페이지 오류 수정, 결제 정보 저장

- src/app/(non-navbar)/schedule/[id]/_component/CalenderDays.tsx
- src/app/(non-navbar)/schedule/[id]/_component/Days.tsx
- src/app/(non-navbar)/schedule/[id]/_component/NotFoundForSchedule.tsx
- src/app/(non-navbar)/schedule/[id]/_component/SelectedProduct.tsx
- 스케줄 선택 페이지에 404페이지를 추가하였습니다.
- 코드가 길어 보이지만 컴포넌트 분리만 해서 코드 변화는 크게 없습니다.
X
> Feat: 스케줄 선택 페이지 404페이지 추가

- src/api/signin/getKakaoAuth.ts
- src/api/signin/getNaverAuth.ts
- src/app/(non-navbar)/email-signin/_component/CertificationCount.tsx
- src/app/(non-navbar)/email-signin/_component/EmailSigninForm.tsx
- src/app/(non-navbar)/email-signup/_component/EmailAuth.tsx
- 로그인 페이지 이메일 인증 수정
- 소셜 로그인 api함수 추가
- 소셜 로그인 api함수는 생성만 해 놓은 상태입니다.
X
> Feat: 로그인 페이지 이메일 인증 수정, 소셜 로그인 api함수 추가

- src/api/balance/getPolls.ts
- src/api/signin/getEmailAuth.ts
- src/api/signin/postCertification.ts
- src/api/signin/postSignin.ts
- src/api/signin/postSignup.ts
- src/app/(non-navbar)/balance/_component/ViewOption.tsx
- src/app/(non-navbar)/balance/page.tsx
- src/app/(non-navbar)/email-signin/_component/EmailSigninForm.tsx
- src/app/(non-navbar)/email-signup/_component/EnterPassword.tsx
- src/hooks/query/useGetPollsQuery.ts
> Fix: 로그인 api수정 및 타입 수정

- src/app/(navbar)/payment/_component/ReservationInfo.tsx
상세페이지 -> 결제페이지 데이터 바인딩 구현하였습니다.
❌
❌
> 상세페이지 -> 결제페이지 데이터 바인딩

- src/api/balance/getPolls.ts
- src/api/balance/getPollsResult.ts
- src/api/balance/postPolls.ts
- src/api/items/getPackageDetail.ts
- src/api/items/getPackageReviews.ts
- src/api/items/getPackageScore.ts
- src/api/schedule/getAvailableDates.ts
- src/api/schedule/getPackageSchedules.ts
- src/api/signin/getEmailAuth.ts
- src/api/signin/getKakaoAuth.ts
- src/api/signin/getNaverAuth.ts
- src/api/signin/postCertification.ts
- src/api/signin/postSignin.ts
- src/api/signin/postSignup.ts
- api요청 함수 try catch문 추가와 console 제거 리팩토링입니다.
X
X
> Refactor: api요청 함수 수정

- .eslintrc.json
- src/app/(non-navbar)/items/[id]/_component/Introduction.tsx
- src/app/(non-navbar)/items/[id]/page.tsx
- ssr에서 prefetch할 때 쿠키가 포함 안 돼서 실제 페이지에서 다른 정보가 표시되는 오류를 수정하였습니다.
X
X
> Refactor: 상세 페이지 prefetch 오류 수정

- src/app/(navbar)/compare/_component/ChangeCompareProduct.tsx
- src/app/(navbar)/compare/_component/MyPicProduct.tsx
- src/app/(navbar)/compare/_component/ProductSummary.tsx
- src/app/(navbar)/compare/_component/WishListInfo.tsx
- src/app/(navbar)/compare/_component/WishListNone.tsx
- src/app/(navbar)/compare/_component/WishListPage.tsx
- src/app/(navbar)/compare/page.tsx
비교페이지와 찜 페이지 퍼블리싱을 끝냈습니다.
❌
❌
> Feat: 비교페이지+찜 페이지 구현 및 수정

- src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
- src/app/(non-navbar)/items/[id]/_component/DetailTypography.tsx
- src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
- src/app/(non-navbar)/items/[id]/_component/StorePerson.tsx
- src/app/_component/common/atom/ScrollToUpButton.tsx
- 상세 페이지에서 로그인 유저를 구분하는 로직을 추가하였습니다.
- 실제 데이터를 반영하여 패키지 인원 선택 시 최소인원, 최대인원을 구분하며 만족하지 못할 시 에러 메시지가 출력 되도록 수정하였습니다.
- 위로 스크롤 해주는 버튼의 위치를 수정하였습니다.
X
X
> Refactor: 상세 페이지 리팩토링

- src/app/(non-navbar)/items/[id]/_component/DetailBottomButton.tsx
- src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
- 상세 페이지 예약 모달 최상단 적용 안되는 오류 해결
- 로그인 페이지 진입시 redirect url 적용
X
X
> Fix: 상세 페이지 예약 모달 최상단 적용 안되는 오류 해결

- src/app/(non-navbar)/email-signin/_component/EmailSigninForm.tsx
- src/app/(non-navbar)/email-signin/_component/SigninInput.tsx
- src/app/(non-navbar)/email-signin/_component/TermsForm.tsx
- src/app/(non-navbar)/email-signup/_component/EmailAuth.tsx
- src/app/(non-navbar)/email-signup/_component/EnterPassword.tsx
- src/app/(non-navbar)/email-signup/_component/SignupComplete.tsx
- src/app/(non-navbar)/signin/page.tsx
- src/app/_component/common/layout/Dialog.tsx
- src/hooks/query/useGetEmailAuthQuery.ts
- src/hooks/query/usePostCertificationMutation.ts
- src/hooks/query/usePostSigninMutation.ts
- src/hooks/query/usePostSignupMutation.ts
- 로그인, 회원가입 모든 로직의 에러메시지를 수정하였습니다.
- 로그인 페이지 진입 시점에 따른 redirect url을 추가하였습니다.
X
X
> Refactor: 로그인, 회원가입 에러 메시지 수정, redirect url 추가

- src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
- src/app/_component/common/atom/ScrollToUpButton.tsx
- tailwind.config.ts
- 상세 페이지 스크롤 버튼이 최상단에서 안 보이도록 수정하였습니다.
X
X
> Refactor: 상세 페이지 스크롤 버튼 애니메이션 수정

- src/api/my/deleteMyAccount.ts
- src/api/my/logout.ts
- src/app/(navbar)/my/menu/_component/AuthItems.tsx
- src/mocks/handlers.ts
- msw 회원탈퇴 추가
- 로그아웃 api
- 회원 탈퇴 api
- 각 메뉴에 api 연동
> Feat: 로그아웃, 회원탈퇴 api 연동

- src/api/search/getHashtagSearchResult.ts
- src/api/search/getKeywordSearchResult.ts
- src/app/(navbar)/search-filter/_component/SearchButton.tsx
- src/app/(navbar)/search-filter/_hooks/useSearchCount.ts
- src/app/(navbar)/search-result/_component/Option.tsx
- src/app/(navbar)/search-result/_component/Options.tsx
- src/app/(navbar)/search-result/_component/Package.tsx
- src/app/(navbar)/search-result/_component/PackagesList.tsx
- src/app/(navbar)/search-result/_component/SearchEmpty.tsx
- src/app/(navbar)/search-result/_component/SearchResult.tsx
- src/app/(navbar)/search-result/_hooks/useHashtagResult.ts
- src/app/(navbar)/search-result/_hooks/useKeywordResult.ts
- src/app/(navbar)/search-result/page.tsx
- src/app/(navbar)/search/_component/Keyword.tsx
- src/app/(navbar)/search/_component/Package.tsx
- src/app/(navbar)/search/_component/PackagesList.tsx
- src/app/(navbar)/search/_component/SearchHeader.tsx
- src/app/types.ts
- src/hooks/query/useHashtagSearchQuery.ts
- src/hooks/query/useKeywordSearchQuery.ts
- src/mocks/handlers.ts
검색 결과 페이지 구성 중입니다 
핸들러 수정했어요!
❌
> Feat: 검색 결과페이지 api 연결

- src/app/(navbar)/search-result/_component/Option.tsx
- src/app/(navbar)/search-result/_component/Package.tsx
- src/app/(navbar)/search-result/_component/PackagesList.tsx
- src/app/(navbar)/search-result/_component/SearchResult.tsx
- src/app/(navbar)/search-result/page.tsx
- src/app/(navbar)/search/_component/Package.tsx
- 해시태그 부분 커스텀했습니당
- 아이템 리스트 부분 보여줍니다!
아직 기능 구현 전입니다아
❌
> Feat: 검색 결과 페이지 퍼블리싱

- src/app/(non-navbar)/items/[id]/_component/DetailBottomButton.tsx
- src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
- src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
- src/app/(non-navbar)/items/[id]/page.tsx
> Fix: 결제 인원 선택 모달 인원 오류 수정

- src/app/(non-navbar)/signin/_component/KakaoLoginButton.tsx
- src/app/(non-navbar)/signin/_component/NaverLoginButton.tsx
> Fix: 소셜 로그인 api 수정

- src/app/(non-navbar)/items/[id]/_component/DetailBottomButton.tsx
- src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
- src/app/_component/common/layout/BottomSlideModal.tsx
- 결제 인원 선택 모달이 하단에 고정되어 나오도록 수정하였습니다.
> Fix: 결제 인원선택 모달 작동 위치 변경

- src/api/items/getPackageDetail.ts
- src/app/(non-navbar)/items/[id]/page.tsx
- 패키지 상세 정보 api요청이 ssr에서 prefetch될때 쿠키가 포함되도록 수정하였습니다.
> Fix: 패키지 상세 정보 api 쿠키 정보 추가

- src/api/home/deleteWish.ts
- src/api/home/postIsWish.ts
- src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
- src/app/(non-navbar)/items/[id]/_component/InclusionExclusionContainer.tsx
- src/app/_component/common/atom/LikeButton.tsx
- src/hooks/query/useDeleteWishMutation.ts
- src/hooks/query/useIsWishMutation.ts
- 좋아요 기능을 추가하였습니다.
- 로그인 안 된 유저는 로그인페이지 이동 모달창이 뜨며 로그인 창으로 이동할 수 있습니다.
```typescript
const getUrl = () => {
if (searchParams.get("departDate")) {
return `${pathname}?departDate=${searchParams.get("departDate")}`;
} else {
return `${pathname}`;
}
};
<LikeButton
id={packageDetail.data.packageId}
isWish={packageDetail.data.isWish}
styleClass="mr-0" // 스타일
signinRedirect={getUrl()} // 로그인 후 redirect될 url
/>
```
- styleClass는 상세 페이지에서는 따로 position이 달라서 추가했습니다. 필수는 아니고 속성을 넣지 않으면 기존 스타일이 그대로 적용됩니다.
- signinRedirect는 로그인 안 된 유저가 좋아요 버튼을 누르면 로그인 페이지 이동 모달이 뜨고, 로그인을 끝내면 다시 이동될 url입니다. 해당 페이지에 searchParam이 있으시면 따로 속성을 넣으시면 되고 아닐 시 기본값으로 해당 pathname이 적용됩니다.
- 로그인 페이지 이동 모달이 정상적으로 뜨는지 페이지마다 확인이 필요합니다.
> Feat: 좋아요 기능 추가

- src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
- src/app/(non-navbar)/items/[id]/_component/ScheduleDetail.tsx
- src/app/(non-navbar)/schedule/[id]/_component/CalenderDays.tsx
- src/hooks/query/usePackageDetailQuery.ts
- 상세 페이지에서 로그인 창 이동 후 로그인하고 돌아오면 새로운 데이터가 적용이 안 되어 좋아요 표시가 활성화 안되는 문제를 해결하였습니다.
> Fix: 디테일 페이지 데이터 fetch오류 수정

- package-lock.json
- package.json
- src/api/my/getMyInfo.ts
- src/api/my/patchMyInfo.ts
- src/api/my/putMyPassword.ts
- src/app/(navbar)/my/_component/ReservationItem.tsx
- src/app/(navbar)/my/_component/ReservationTabContent.tsx
- src/app/(navbar)/my/menu/reservation/page.tsx
- src/app/(non-navbar)/my/info/_components.tsx/AddressSearch.tsx
- src/app/(non-navbar)/my/info/_components.tsx/InputWithButton.tsx
- src/app/(non-navbar)/my/info/page.tsx
- src/app/types.ts
- src/hooks/query/useUpdateMyInfoMutation.ts
- src/hooks/query/useUpdatePasswordMutation.ts
- src/mocks/handlers.ts
- src/utils/formatPhoneNumber.ts
- 회원 정보 수정 퍼블리싱
- 회원정보 등록 / 수정 api 연동 및 기능 추가
- 카카오 우편번호 api 연동
카카오 우편번호 api 타입스크립트 사용을 위해 아래 패키지 설치하였습니다!
"@types/daum-postcode": "^2.0.3
npi -i 부탁드립니다!
> Feat : 회원정보 등록 / 수정 기능

- src/app/(navbar)/search-result/_component/Option.tsx
- src/app/(navbar)/search-result/_component/Options.tsx
- src/app/(navbar)/search-result/_hooks/useHashtagResult.ts
- src/app/(navbar)/search-result/_hooks/useOptions.ts
- src/app/(navbar)/search-result/page.tsx
검색필터 -> 검색 결과 페이지로 이동했을경우 선택된 옵션 삭제후 다시 새로운 데이터 받아오는 로직 추가했숨니당,,,,,,,🫠
❌
❌
> Feat: 검색 결과페이지에서 선택된 옵션 삭제 기능

- src/app/(non-navbar)/my/info/page.tsx
> Fix:정보 수정 후 페이지 이동 수정

- src/api/signin/getKakaoAuth.ts
- src/api/signin/getNaverAuth.ts
> Fix: Oauth API credentials 제거

- src/api/signin/getKakaoAuth.ts
- src/api/signin/getNaverAuth.ts
> Fix: 소셜 로그인 api수정

- src/api/signin/getNaverAuth.ts
- src/app/(non-navbar)/signin/_component/KakaoLoginButton.tsx
- src/app/(non-navbar)/signin/_component/NaverLoginButton.tsx
> Fix: Oauth API 수정

- src/app/(navbar)/search-result/_component/DropDownBox.tsx
- src/app/(navbar)/search-result/_component/DropDownOption.tsx
- src/app/(navbar)/search-result/_component/Option.tsx
- src/app/(navbar)/search-result/_component/SearchResult.tsx
- src/app/constants.ts
결과페이지에서 사용자가 정렬순서 선택할 수 있는 기능 추가했습니다!
❌
❌
> Feat: 검색 결과페이지 정렬 추가

- src/app/(navbar)/search/_component/PackagesList.tsx
> Fix: 검색 페이지 데이터 뎁스 수정

- src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
- src/app/(non-navbar)/items/[id]/_component/DetailSwiper.tsx
- src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
- src/app/_component/common/atom/ScrollToUpButton.tsx
- src/app/_component/common/layout/BottomSlideModal.tsx
- src/app/_component/common/layout/Dialog.tsx
- 스크롤 위로가기 버튼의 위치와 동작 애니메이션을 수정하였습니다.
- 로그인 경고 모달이 이상한 위치에서 보이는 현상을 수정하였습니다.
- 스와이퍼 컴포넌트에 delay속성을 추가하였습니다. 
```javascript
<DetailSwiper imgUrls={packageDetail.data.imageUrls} delay={4}/> // 2는 2초, 4는 4초 "none"은 수동 (기본값: none)
```
X
X
> Refactor: 상세 페이지

- src/app/(navbar)/error.tsx
- src/app/(non-navbar)/error.tsx
- 에러 페이지의 버튼 스타일을 수정하였습니다.
X
X
> Design: 에러 페이지 버튼 디자인 수정

- src/app/(non-navbar)/balance/page.tsx
- src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
- src/app/(non-navbar)/items/[id]/_component/Reviews.tsx
- src/app/_component/common/layout/DefaultHeader.tsx
- src/hooks/query/usePackageReveiwQuery.tsx
> Fix: 헤더 이동 url속성 추가

- src/api/heart/getWishList.ts
- src/app/(navbar)/heart/_component/Tag.tsx
- src/app/(navbar)/heart/_component/Wish.tsx
- src/app/(navbar)/heart/_component/WishesList.tsx
- src/app/(navbar)/heart/page.tsx
- src/app/_component/common/atom/LikeButton.tsx
- src/hooks/query/useGetWishListQuery.ts
찜리스트 보여주기 구현했숨니당 추후 무한스크롤 호다닥 추가할게요
❌
❌
> Feat: 찜페이지 기능 구현

- src/app/(navbar)/compare/_component/ChangeCompareProduct.tsx
- src/app/(navbar)/compare/_component/MyPicProduct.tsx
- src/app/(navbar)/compare/_component/WishListInfo.tsx
- src/app/(navbar)/compare/_component/WishListPage.tsx
- src/app/(navbar)/compare/page.tsx
> Feat: 상품 비교 상품 선택 기능

- src/app/(non-navbar)/theme/[id]/_component/BestThemeDetail.tsx
- src/app/(non-navbar)/theme/[id]/_component/ThemeDetail.tsx
- src/hooks/query/usePackageListQuery.tsx
각 테마 페이지 내 대표 이미지의 object-fill 속성을 cover로 적용합니다!
X
X
> Refactor: 테마 페이지 패키지 이미지 속성 수정

- src/api/my/getMyReviews.ts
- src/app/(navbar)/my/_component/MyReviewTabContent.tsx
- src/hooks/query/useMyReviewsQuery.ts
> Feat: 내가 작성한 리뷰 무한스크롤 구현

- src/app/(navbar)/compare/_component/ChangeCompareProduct.tsx
- src/app/(navbar)/compare/_component/MyPicProduct.tsx
- src/app/(navbar)/compare/_component/WishListInfo.tsx
- src/app/(navbar)/compare/_component/WishListPage.tsx
- src/app/(navbar)/compare/page.tsx
- src/app/(non-navbar)/items/[id]/_component/BadgeList.tsx
- src/app/(non-navbar)/items/[id]/_component/DetailBottomButton.tsx
- src/app/(non-navbar)/items/[id]/_component/PackageTagBadge.tsx
- src/app/(non-navbar)/items/[id]/_component/ReviewItem.tsx
- src/app/(non-navbar)/items/[id]/_component/Reviews.tsx
- src/hooks/query/usePackageReveiwQuery.tsx
> Fix: 상세 페이지, 상품 비교 연동 및 수정

- src/app/(non-navbar)/balance/_component/ViewOption.tsx
- src/app/(non-navbar)/balance/page.tsx
> Fix: 찬반 페이지 이벤트 없을때 예외 추가

- src/app/(non-navbar)/balance/page.tsx
> Fix: 찬반 페이지 메타데이터 타이틀 수정

- src/api/home/getSalePackages.ts
- src/app/(navbar)/heart/_component/Tag.tsx
- src/app/(navbar)/heart/_component/Wish.tsx
> Feat: 찜페이지에서 좋아요 해제

- next.config.js
- src/app/(navbar)/compare/_component/ChangeCompareProduct.tsx
- src/app/(navbar)/compare/_component/LeftProgressBar.tsx
- src/app/(navbar)/compare/_component/RightProgressBar.tsx
비교페이지 쇼핑센터 방문일정 부분을 수정하였습니다.
금액부분 3자리마다 콤마(,)가 찍히도록 구현하였습니다.
X
X
> Fix: 비교페이지 쇼핑센터 방문일정 부분 수정

- src/app/(navbar)/my/_component/UpcomingPackage.tsx
> Design: 다가오는 패키지 너비 반응형 고려한 사이즈로 변경

- src/app/(navbar)/compare/_component/ChangeCompareProduct.tsx
> Fix: 비교페이지 쇼핑센터 방문일정 오류 해결

- src/app/(navbar)/compare/_component/LeftProgressBar.tsx
- src/app/(navbar)/compare/_component/RightProgressBar.tsx
> Fix: 프로그레스바 오류수정2

- src/app/(navbar)/compare/_component/ChangeCompareProduct.tsx
> Fix: 프로그레스바 오류수정3

- src/app/(navbar)/compare/_component/LeftProgressBar.tsx
- src/app/(navbar)/compare/_component/RightProgressBar.tsx
> Fix: 프로그레스바 오류수정

- src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
- src/app/(non-navbar)/items/[id]/_component/DetailSwiper.tsx
- src/app/(non-navbar)/items/[id]/_component/SwiperBadge.tsx
- src/app/_component/home/HomeAdvertisements.tsx
> Feat: 이미지 슬라이드 메인 테마 추가

- src/app/(navbar)/compare/_component/ChangeCompareProduct.tsx
- src/app/(navbar)/compare/_component/LeftProductSummary.tsx
- src/app/(navbar)/compare/_component/LeftProgressBar.tsx
- src/app/(navbar)/compare/_component/MyPicProduct.tsx
- src/app/(navbar)/compare/_component/RightProductSummary.tsx
- src/app/(navbar)/compare/_component/RightProgressBar.tsx
- src/app/(navbar)/compare/_component/WishListPage.tsx
- src/app/(navbar)/compare/page.tsx
> Design: 비교 페이지 UI 개선

- src/app/(navbar)/my/_component/MyReviewTabContent.tsx
> Chore: 오타수정

- src/api/my/deleteMyAccount.ts
- src/api/my/getFaqDetail.ts
- src/api/my/getMyOrderList.ts
- src/api/my/getMyOrders.ts
- src/api/my/getMyUpcomingPackage.ts
- src/api/my/getNoticeDetail.ts
- src/api/my/getNoticeList.ts
- src/api/my/getOrderToReview.ts
- src/api/my/logout.ts
- src/app/(navbar)/my/_component/MyReviewTabContent.tsx
- src/app/(navbar)/my/_component/ReservationItem.tsx
- src/app/(navbar)/my/_component/ReservationTabContent.tsx
- src/app/(navbar)/my/_component/Skeleton.tsx
- src/app/(navbar)/my/_component/SkeletonText.tsx
- src/app/(navbar)/my/_component/SkeletonTitle.tsx
- src/app/(navbar)/my/_component/UpcomingPackage.tsx
- src/app/(navbar)/my/_component/UserInfo.tsx
- src/app/(navbar)/my/menu/_component/AuthItems.tsx
- src/app/(navbar)/my/menu/faq/[id]/page.tsx
- src/app/(navbar)/my/menu/faq/page.tsx
- src/app/(navbar)/my/menu/notice/[id]/page.tsx
- src/app/(navbar)/my/menu/notice/page.tsx
- src/app/(non-navbar)/my/info/page.tsx
- src/utils/canWriteReview.ts
- 마이페이지 첫 화면 스켈레톤 적용
- 콘솔 제거
-
> Design: 스켈레톤 적용

- src/app/(non-navbar)/theme/[id]/_component/BestThemeDetail.tsx
> Refactor: 이미지 너비 값 수정

- src/app/(navbar)/search-filter/_component/Concept.tsx
- src/app/(navbar)/search-filter/_component/Destination.tsx
- src/app/(navbar)/search-filter/_component/PriceRangeBar.tsx
- src/app/(navbar)/search-result/page.tsx
- src/app/(navbar)/search/_component/SearchHeader.tsx
- src/store/useSearchFilterStore.ts
> Refactor: 검색 페이지 자잘한 이슈 해결

- src/app/(navbar)/compare/_component/ChangeCompareProduct.tsx
- src/app/(navbar)/compare/_component/MyPicProduct.tsx
- src/app/(navbar)/compare/page.tsx
- src/app/(navbar)/my/review/_components/ReviewForm.tsx
> Fix: 리뷰 별점 초기값 변경

- src/app/(navbar)/payment/_component/ReservationInfo.tsx
> Fix: 전체 약관동의 버튼 제거

- src/app/(navbar)/compare/_component/ChangeCompareProduct.tsx
- src/app/(navbar)/compare/page.tsx
- src/app/(non-navbar)/email-signup/_component/SignupComplete.tsx
- src/app/_component/common/atom/NavIconButton.tsx
- src/app/_component/common/layout/BottomNav.tsx
- src/app/_component/common/layout/DefaultHeader.tsx
- 비교 페이지 10개 이하 상품 조건 추가
- 하단 바 스크롤중이 아니면 화면에 표시
- 회원가입 사용자 이름 표시 
- 비교 페이지 뒤로가기 오류 수정
> Fix: 비교 페이지 조건 추가, 하단 바 스크롤 조건 변경

- src/app/(navbar)/search-filter/_component/SearchButton.tsx
> Refactor: 검색 필터 페이지 버튼 항상 하단에 노출

- next.config.js
- src/app/(navbar)/heart/page.tsx
- src/app/(navbar)/search-result/_component/Package.tsx
- src/app/_component/common/atom/Button.tsx
- src/app/_component/common/layout/Dialog.tsx
- src/hooks/useDefaultImage.ts
> Refactor: 검색 결과 페이지 이미지 최적화 + 이미지 로드 에러시 대체 이미지 설정

- src/api/my/getFaqList.ts
- src/app/(navbar)/my/menu/_component/DataListItem.tsx
- src/app/(navbar)/my/menu/faq/[id]/page.tsx
- src/app/(navbar)/my/menu/faq/page.tsx
- src/app/(navbar)/my/menu/notice/[id]/page.tsx
- src/app/(navbar)/my/menu/notice/page.tsx
- src/app/_component/common/layout/SmallSpinner.tsx
- src/app/types.ts
- src/hooks/query/useFaqDetailQuery.ts
- src/hooks/query/useNoticeDetailQuery.ts
> Feat: 공지사항 줄바꿈 및 로딩스피너 추가

- src/app/(navbar)/heart/_component/Wish.tsx
- src/app/(navbar)/heart/_component/WishesList.tsx
- src/app/(navbar)/heart/page.tsx
- src/app/(navbar)/search-filter/_component/Concept.tsx
- src/app/(navbar)/search-filter/_component/Destination.tsx
- src/app/(navbar)/search-result/_component/Options.tsx
- src/app/(navbar)/search-result/_component/Package.tsx
- src/app/(navbar)/search-result/_component/PackagesList.tsx
- src/app/(navbar)/search-result/_component/SearchResult.tsx
- src/app/(navbar)/search-result/_component/SkeletonItem.tsx
- src/app/(navbar)/search-result/page.tsx
- src/hooks/useDefaultImage.ts
> Refactor: 자잘한 디자인 수정,,

- src/app/(navbar)/search-filter/_component/Concept.tsx
> Design: 필터 검색 페이지 디테일 수정

- src/app/(navbar)/my/_component/UpcomingPackage.tsx
> Chore: 다가오는 패키지 타이틀 수정

- src/api/my/getMyOrderList.ts
- src/api/my/patchMyInfo.ts
- src/app/(navbar)/my/_component/Chip.tsx
- src/app/(navbar)/my/_component/MyReviewTabContent.tsx
- src/app/(navbar)/my/_component/ReservationItem.tsx
- src/app/(navbar)/my/_component/ReservationTabContent.tsx
- src/app/(navbar)/my/_component/ReviewButton.tsx
- src/app/(navbar)/my/_component/Skeleton.tsx
- src/app/(navbar)/my/_component/SkeletonTitle.tsx
- src/app/(navbar)/my/menu/_component/DataList.tsx
- src/app/(navbar)/my/menu/reservation/_component/ReservationMain.tsx
- src/app/(navbar)/my/review/_components/RangeSlider.tsx
- src/app/(navbar)/my/review/_components/WriteReview.tsx
- src/app/(non-navbar)/my/info/_components.tsx/AddressSearch.tsx
- src/app/(non-navbar)/my/info/page.tsx
- src/app/_component/common/layout/Dialog.tsx
- src/app/_component/common/layout/SmallSpinner.tsx
- src/hooks/query/useMyOrdersQuery.ts
- src/hooks/query/useUpdateMyInfoMutation.ts
- src/hooks/useOnClickOutside.tsx
- src/utils/sortOrderList.ts
회원정보수정 리팩토링
console.log, 주석 제거
기타 자잘한 디자인 수정
> Refactor: 회원정보수정 리팩토링

- src/app/_component/home/HomeSalePackages.tsx
- src/hooks/query/usePackageListQuery.tsx
> Refactor: 초특가 패키지 개선

- src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
- src/app/_component/common/atom/ScrollToUpButton.tsx
- 하단 바 스크롤 중지 동작 상세 페이지 적용
x
x
> Fix: 하단 바 스크롤 중지 동작 상세 페이지 적용

- src/app/_component/home/HomeAdvertisements.tsx
- src/app/_component/home/HomeThemePackage.tsx
- src/app/page.tsx
> Refactor / 메인 페이지 성능 개선

- src/app/(non-navbar)/email-signin/_component/TermsForm.tsx
- 회원가입 약관 동의 모달 z-index 추가
x
x
> Fix: 회원가입 약관 동의 모달 z-index 추가

- src/app/(non-navbar)/email-signin/_component/EmailSigninForm.tsx
이메일로 로그인 문구 수정 진행했습니다. (이메일 또는 아이디 -> 이메일)
> Refactor: 이메일로 로그인 문구 수정

- src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
- src/app/(non-navbar)/items/[id]/_component/DetailSkeleton.tsx
- src/app/(non-navbar)/theme/[id]/_component/Theme.tsx
- src/app/(non-navbar)/theme/[id]/_component/ThemePackageItem.tsx
- src/app/(non-navbar)/theme/[id]/page.tsx
- src/store/useLoadingStore.ts
- src/store/useScrollYStore.ts
- 상세 페이지 이동 시 상태 관리를 통해 스켈레톤 UI를 보여줌으로써 사용자 경험 개선
- 상세 페이지에서 뒤로가기 시 리스트 페이지 스크롤 복원
X
X
> Refactor: 상세 페이지 피드백 반영 리팩토링

- src/api/my/getOrderToReviewAuth.ts
- src/api/my/patchMyInfo.ts
- src/api/my/putMyPassword.ts
- src/app/(navbar)/compare/page.tsx
- src/app/_component/home/HomeProsAndCons.tsx
> Refactor : 필요없는 코드 삭제
