.eslintrc.json
src/app/_component/Button.tsx
src/app/_component/DefaultHeader.tsx
src/app/email-signin/_component/EmailSigninForm.tsx
src/app/email-signin/_component/SigninInput.tsx
src/app/email-signin/_component/TermsForm.tsx
src/app/email-signin/page.tsx
src/app/email-signup/page.tsx
src/app/signin/_component/SigninHeader.tsx

- 로그인 페이지에서 사용하는 input의 반복되는 애니메이션 때문에 컴포넌트를 분리하였습니다. (이 후 모든 input에 대한 공통 컴포넌트로의 변경을 논의할 예정입니다)
- 헤더 컴포넌트의 테마 속성을 추가하였습니다. 이후 마이 페이지에서의 메뉴 버튼이나 다른 추가 요소는 해당 컴포넌트가 만들어진 후 portals나 조건을 통하여 추가할 예정입니다. 세부적인 스타일 요소도 언제든 수정될 수 있다는 점 참고해주세요. (아래 예시 참조)
- button에 대한 컴포넌트를 생성하였고 테마를 추가하였습니다.  세부적인 스타일 요소도 언제든 수정될 수 있다는 점 참고해주세요. (아래 예시 참조)
```javascript
{
text: string;  // 화면에 표시될 글자
subText?: string; // 화면에 연한 색상으로 표시될 글자
redirectUrl?: string; // 버튼 클릭 시 이동할 주소 (입력 안 하면 이동 버튼 안 생김)
theme?: string; // 원하는 테마 (기본 값: default)
}
```
사용
```javascript
<DefaultHeader text="이메일로 로그인" redirectUrl="/signin" />
```
```javascript
<DefaultHeader
text="회원가입 "
subText={`(${step}/2)`}
redirectUrl="/email-signin"
/>
```
```javascript
<DefaultHeader text="이메일로 로그인" redirectUrl="/signin" theme="main"/>
``` …

Feat: input, header, button 주요 컴포넌트 분리

---

src/app/_component/common/TabButtons.tsx
src/app/_component/common/Tabs.tsx
src/app/_component/common/TabsContainer.tsx
src/app/my/_component/MyReviewTabContent.tsx
src/app/my/_component/ReservationTabContent.tsx
src/app/my/_component/TabTest.tsx
src/app/my/_component/UpcomingPackages.tsx
src/app/my/_component/UserInfo.tsx
src/app/my/_test/Mypage.test.tsx
src/app/my/page.tsx
src/utils/renderStars.tsx

- 공통 탭 컴포넌트 생성
- 마이페이지 퍼블리싱
공통 탭 컴포넌트 생성하였습니다!
- tabs prop을 통해 탭의 이름과 내용을 배열로 받습니다.
- tabButtonStyle prop을 통해 선택된 탭(defaultClass)과 기본 탭(selectedClass)의 스타일을 정의합니다.
- 탭 버튼(buttons)과 탭 컨텐츠(children)를 받아 렌더링합니다.
- 탭 버튼들을 감싸고 있는 ul 태그에 overflow-x-auto 속성 주어 가로 스크롤 가능하도록 하였습니다.
- tabName, onClick, isSelected,defaultClass, selectedClass을 props로 받습니다.
```javascript
const TabTest = () => {
const tabsData = [
{ name: "test1", content: <Test1 /> },
{ name: "test2", content: <Test2 /> },
{ name: "test3", content: <Test3 /> },
];
return (
<>
<TabsContainer
tabs={tabsData}
tabButtonStyle={{
defaultClass: "py-2 border-b border-1 border-gray-400",
selectedClass:
"py-2 text-black border-b border-1 border-pink border-solid",
}}
/>
</>
);
};
export default TabTest;
```
좀 더 단순하게 구성하고 싶었는데 쉽지 않네요..😭 좋은 의견 …

Feat: 공통 탭 컴포넌트 생성 및 마이페이지 퍼블리싱

---

src/app/(non-navbar)/email-signin/_component/CertificationCount.tsx
src/app/(non-navbar)/email-signin/_component/EmailSigninForm.tsx
src/app/(non-navbar)/email-signin/_component/SigninInput.tsx
src/app/(non-navbar)/email-signin/_component/TermsForm.tsx
src/app/(non-navbar)/email-signup/_component/EmailAuth.tsx
src/app/(non-navbar)/email-signup/_component/EnterPassword.tsx
src/app/constants.ts
src/store/useSignupInfoStore.ts
src/store/useSignupStateStore.ts

- 이메일 인증 시 카운트 다운이 진행 됩니다.
- 이메일 인증 상태를 스토어에 추가하였습니다.
- 흐름을 파악하기 쉽도록 일단 카운트를 5초로 해 놓은 상태 입니다. (이후 수정 5분으로 변경 예정)
X

Feat: 이메일 인증 카운트 추가

---

.eslintrc.json
public/icons/pageLeftIcon.svg
public/icons/pageLeftIconLight.svg
public/icons/pageRightIcon.svg
public/icons/pageRightIconLight.svg
src/app/(navbar)/payment/_component/ReservationInfo.tsx
src/app/(non-navbar)/schedule/[id]/_component/Calender.tsx
src/app/(non-navbar)/schedule/[id]/_component/CalenderDays.tsx
src/app/(non-navbar)/schedule/[id]/_component/CalenderHeader.tsx
src/app/(non-navbar)/schedule/[id]/_component/CalenderMonth.tsx
src/app/(non-navbar)/schedule/[id]/_component/CalenderWeeks.tsx
src/app/(non-navbar)/schedule/[id]/_component/SelectedProduct.tsx
src/app/(non-navbar)/schedule/[id]/page.tsx
src/app/layout.tsx

- 일정 선택 페이지에서 연도와 월을 선택하는 화면 레이아웃을 추가하였습니다.
- 오늘을 기준으로 이전 달은 버튼이 비활성화 됩니다.
- 연도와 달을 기준으로 몇일인지 확인하는 기능을 추가하였습니다.
- 추가한 svg파일이 이미 있는 파일일 경우 코멘트 남겨주세요!!
- 이미지만 있는 버튼은 일단 button태그를 사용하였습니다. 이후에 Button공통 컴포넌트에 기능 추가 후 교체 예정입니다.
X

Feat: 일정 선택 연도, 월 선택 추가

---

public/icons/pageRightIconLight.svg
src/app/(non-navbar)/schedule/[id]/_component/Calender.tsx
src/app/(non-navbar)/schedule/[id]/_component/CalenderDays.tsx
src/app/(non-navbar)/schedule/[id]/_component/CalenderHeader.tsx
src/app/(non-navbar)/schedule/[id]/_component/CalenderMonth.tsx
src/app/(non-navbar)/schedule/[id]/_component/CalenderWeeks.tsx
src/app/(non-navbar)/schedule/[id]/_component/SelectedProduct.tsx
src/utils/generateDays.ts
src/utils/getMonthInDate.ts

- 선택한 연도와 월에 따라서 화면에 캘린더가 표시되도록 기능을 추가하였습니다.
- 요일, 현재 날짜에 따라서 캘린더 숫자의 색상이 다르게 표시되도록 기능을 추가하였습니다.
웹
모바일
- 캘린더 구현이 예상보다 코드가 길어져 중간 pr한번 올립니다. 
- 이후에 해당 브랜치에서 캘린더 관련 기본 레이아웃, 기능 작업을 이어갈 예정입니다.
- 이후 스타일 색상도 tailwind 설정에 추가 예정입니다.
X

Feat: 일정 선택 날짜 선택 기능 및 기본 디자인 추가

---

src/api/items/getPackageDetail.ts
src/api/schedule/getAvailableDates.ts
src/app/(non-navbar)/schedule/[id]/_component/CalenderDays.tsx
src/app/(non-navbar)/schedule/[id]/_component/CalenderHeader.tsx
src/app/(non-navbar)/schedule/[id]/_component/CalenderWeeks.tsx
src/app/(non-navbar)/schedule/[id]/_component/SelectedProduct.tsx
src/app/(non-navbar)/schedule/[id]/page.tsx
src/app/types.ts
src/mocks/data/packageScheduleData.ts
src/mocks/handlers.ts
src/store/useScheduleDateStore.ts

- 캘린더의 동작이 MSW서버의 요청에 따라서 동작하도록 기능을  추가하였습니다.
- 상품의 데이터를 연결하였습니다.
- 초기 진입 시 선택된 상품의 스켈레톤 UI를 추가하였습니다.
- 패키지 스케줄 표시를 위한 데이터를 추가했습니다. (이후 제거 예정)
- 스케줄 가짜 데이터의 추가로 코드가 길어 보일 수 있습니다.
- type.ts 폴더를 변경하였습니다.
- handlers.ts 폴더를 변경하였습니다.

Feat: 캘린더 상품 데이터 MSW연결

---

src/app/_component/common/layout/DefaultHeader.tsx
src/app/_component/home/HomeHashtags.tsx
src/app/page.tsx

- 메인 페이지에서 헤더 좌측에 기타 페이지처럼 화살표가 생성되고, 온클릭 메서드를 통해 뒤로 가기 동작이 이루어지던 부분을 수정했습니다.
- 기존 `redirectUrl ? ... : ... `와 같이 redirectUrl로의 이동인지, 혹은 router.back() 메서드를 통한 뒤로 가기 이동인지 구분하던 삼항연산자 로직을 감싸는 새로운 삼항연산자 로직을 작성했습니다.
- true 조건은 넘겨받은 theme이 default일 때이며, theme이 main인 경우에는 false 조건으로 null을 반환하고, 화살표가 노출되지 않게 합니다.
- 메인 페이지에서 하단 네비게이션 바의 위치가 부자연스럽고 375 x 812 모바일 뷰를 벗어난 경우, 하단 네비게이션 바가 우측으로 밀려나던 현상을 수정했습니다.
- 기존 `<section>` 태그 안에서 요소를 가운데 정렬하기 위해 사용했던 `mx-auto` 코드가 원인이었습니다. 
- `(navbar) > layout.tsx` 의 디자인을 참고해 수정하였습니다!
X

Feature: 메인 페이지 레이아웃 수정 / 해시태그 버튼 디자인 수정

---

src/app/(non-navbar)/items/[id]/_component/DetailBottomButton.tsx
src/app/(non-navbar)/items/[id]/_component/DetailMoreButton.tsx
src/app/(non-navbar)/items/[id]/_component/DetailSwiper.tsx
src/app/(non-navbar)/items/[id]/_component/DettailMain.tsx
src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
src/app/(non-navbar)/items/[id]/_component/SwiperBadge.tsx
src/app/(non-navbar)/items/[id]/page.tsx
src/hooks/query/usePackageDetailQuery.ts
src/mocks/data/packageScheduleData.ts

- 상세 페이지에 이미지 캐러셀을 추가 하였습니다.
(마우스 or 2.5초 후 다음 이미지, 이미지 순서 숫자 표시)
- 데이터를 MSW와 연결하였습니다.
웹
모바일
- 스타일은 지속적으로 바뀔 수 있어서 스타일을 제외한 기능을 바탕으로 리뷰 해주시면 감사드리겠습니다.
X

Feat: 상세페이지 이미지 캐러셀 추가, 데이터 MSW연결

---

src/app/(non-navbar)/items/[id]/_component/ChangeDateButton.tsx
src/app/(non-navbar)/items/[id]/_component/DetailBottomButton.tsx
src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
src/app/(non-navbar)/items/[id]/_component/DetailMoreButton.tsx
src/app/(non-navbar)/items/[id]/_component/DetailTypography.tsx
src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
src/app/(non-navbar)/items/[id]/_component/TravelDate.tsx
src/app/(non-navbar)/items/[id]/page.tsx
src/app/(non-navbar)/items/page.tsx
src/app/(non-navbar)/schedule/[id]/_component/SelectedProduct.tsx
src/utils/ReplaceHyphenWithDot.ts
tailwind.config.ts

- 웹에서 글자가 좀 더 크게 보이도록 컴포넌트를 수정하였습니다.
- 날자 데이터 문자 변경 함수를 유틸 함수로 분리하였습니다.  ex) "2024-03-02" -> "2024.03.02" 
- 상세 페이지 레이아웃을 추가 하였습니다.
- 상세 페이지 items -> page.tsx는 배포 확인 용 임시 코드입니다.
X
X

Feat: 상세 페이지 타이포그래피 컴포넌트 글자 웹 크기 추가, 레이아웃 추가

---

src/app/(navbar)/payment/_component/ReservationDone.tsx
src/app/(navbar)/payment/_component/ReservationInfo.tsx
src/app/(navbar)/payment/_component/TopStatus.tsx

결제페이지 퍼블리싱과 프론트기능구현 완료하였습니다. API만 연결하면 될것같습니다.
API연결전에 비교페이지 작업먼저 하겠습니다.
프로그레스바가 동적으로 순서에따라 차오릅니다.
약관을 전부읽어야 전부동의가 됩니다.
프로그레스바가 100%일때 예약완료 버튼이 활성화 됩니다.!
동영상봐주시면 좋을것 같습니다.!
프로그레스바를 sticky로 위에 붙여 두었는데 어떤가요? 피드백 부탁드립니다
https://github.com/yanolja-finalproject/LETS_FE/assets/59171592/ce35c3fb-409c-4acc-8d4d-b0c70d17b72a
❌

Feat: 결제페이지 프론트기능구현끝

---

src/api/items/getPackageReviews.ts
src/api/items/getPackageScore.ts
src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
src/app/(non-navbar)/items/[id]/_component/ReviewItem.tsx
src/app/(non-navbar)/items/[id]/_component/ReviewRange.tsx
src/app/(non-navbar)/items/[id]/_component/ReviewRangeList.tsx
src/app/(non-navbar)/items/[id]/_component/Reviews.tsx
src/app/(non-navbar)/items/[id]/_component/ScheduleDetail.tsx
src/app/(non-navbar)/items/[id]/page.tsx
src/app/types.ts
src/hooks/query/usePackageReveiwQuery.tsx
src/hooks/query/usePackageScoreQuery.tsx
src/mocks/data/packageScheduleData.ts
src/mocks/handlers.ts
tailwind.config.ts

- 패키지 리뷰 목록을 추가했습니다.
- 무한 스크롤을 통해 데이터를 가져올 수 있도록 하였습니다.
- 리뷰 아이템은 기존 마이 페이지에 있는 기본 틀을 그대로 가져다 따로 컴포넌트로 만들었습니다. 거의 똑같은 거라 공통으로 그냥 쓰면 되지만 함부로 수정했다가 마이 페이지의 레이아웃이 망가질까 봐 일단 따로 다시 만들었고, 이후 리팩토링 과정에서 합치면 좋을 거 같습니다.

Feat: 상세 페이지 리뷰 데이터 연동 및 무한 스크롤 추가

---

src/app/(navbar)/payment/_component/ReservationInfo.tsx

결제페이지 안변하는 값 하드코딩만 조금 했습니다.
브랜치를 새로 분기했는데 이미 feature/compare에 커밋해버려서 해당pr올립니다.
❌
❌

Style: 결제페이지 값 하드코딩

---

src/app/(non-navbar)/items/[id]/_component/NoReviews.tsx
src/app/(non-navbar)/items/[id]/_component/Reviews.tsx

- 배포 환경에서 리뷰가 없으면 무한으로 요청 보내지는 현상으로 인해 리뷰 없을 때 화면을 추가했습니다.
- 이후 로그인 되어 있으면 마이 페이지 아니면 로그인 페이지로 이동 되도록 만들 예정입니다.
- 해당 404 컴포넌트를 text로 받아서 공통으로 사용하는 부분은 이후에 고려해보겠습니다.
X

Feat: 리뷰 없을 때 화면 추가

---

src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
src/app/(non-navbar)/items/[id]/_component/NoReviews.tsx
src/app/(non-navbar)/items/[id]/_component/Reviews.tsx
src/app/_component/common/layout/Dialog.tsx
src/app/_component/common/layout/TabsContainer.tsx

- 상세 페이지에서 로그인 유저가 구분되도록 하였습니다.
- 탭 컴포넌트에서 scroll속성을 주면 (기본값 false) 스크롤이 해당 탭보다 아래로 내려가 있을 때 탭을 클릭하면 스크롤이 탭 위치까지 이동됩니다.
- 상세 페이지의 주석된 부분을 활성화하면 실제 로그인 유저에 대한 구분을 합니다. 이 부분은 로그인 오류 해결 후 다시 활성화할 예정입니다.
X

Feat: 상세 페이지 로그인 유저 구분, 탭 컴포넌트 스크롤 속성 추가

---

package.json
server.js

- 로컬에서 https로 서버가 돌아갈 수 있도록 커스텀 서버를 추가 하였습니다. 
- localhost도메인 이름을 다른 이름으로 실행시키는 방법이랑 가짜 인증서 받는 방법 위키에 적어 놨습니다.
[wiki링크
](https://github.com/yanolja-finalproject/LETS_FE/wiki/next.js-%EC%84%9C%EB%B2%84-https%EB%A1%9C-%EC%8B%A4%ED%96%89%EC%8B%9C%ED%82%A4%EA%B8%B0)

Env: 로컬 환경 커스텀 https서버 추가

---

src/api/my/getMyInfo.ts
src/api/my/getMyOrders.ts
src/api/my/getMyUpcomingPackage.ts
src/app/(navbar)/my/_component/ReservationTabContent.tsx
src/app/(navbar)/my/_component/UpcomingPackage.tsx
src/app/(navbar)/my/_component/UpcomingPackages.tsx
src/app/(navbar)/my/menu/_component/DataListItem.tsx
src/app/(navbar)/my/menu/reservation/page.tsx
src/app/(navbar)/my/page.tsx
src/hooks/query/useMyOrdersQuery.ts
src/hooks/query/useMyUpcomingPackageQuery.ts
src/hooks/useInfiniteScroll.ts
src/mocks/handlers.ts

- mock데이터 응답구조 및 api return값 수정
mock데이터에 응답구조가 잘못들어가서 로컬에선 정상노출됐지만 배포사이트에서 노출되지 않는 점 확인하고 수정하였습니다!
+) 마이페이지 탭 영역 예약내역 무한스크롤
+) 마이페이지 -> 메뉴 -> 예약내역 무한 스크롤

Feat: 예약내역 무한스크롤

---

next.config.js
src/api/advertisement/getAdvertisementInfo.ts
src/app/(non-navbar)/advertisement/[id]/_component/AdvertisementInfomation.tsx
src/app/(non-navbar)/advertisement/[id]/page.tsx
src/app/_component/home/HomeAdvertisements.tsx
src/app/page.tsx
src/app/types.ts
src/hooks/query/useAdvertisementInfoQuery.ts
src/mocks/handlers.ts
src/utils/formatLongText.ts
src/utils/getAdsHeaderText.ts

200_광고 및 프로모션 구좌 페이지 퍼블리싱 진행하였습니다!
- 메인 페이지 상단의 광고구좌 슬라이드를 선택해 해당 광고 페이지로 이동합니다.
- /advertisement/{id} 의 URL 구조로 이동합니다.
- 해당 페이지에서는 광고구좌 목록 조회(v1/advertisements/), 광고구좌 조회(v1/advertisements/{id}) 두 API를 호출합니다.
- 광고구좌 목록 조회(v1/advertisements/)의 경우는 광고구좌 페이지 상단에서의 슬라이드 노출을 위해서,
- 광고구좌 조회(v1/advertisements/{id})는 광고구좌 내 패키지상품 나열을 위해 사용합니다.
- 200_광고 및 프로모션 페이지 내에서는 사용하지 않았지만, 텍스트 길이가 긴 문자열에 대해 말줄임표 (...) 를 붙이는 util 컴포넌트 (formatLongText.ts)를 추가했습니다!
- utils 폴더 안에 위치하고 있습니다.
- 인자로는 원본 문자열과 제한할 숫자 길이를 받습니다.
- 전달받은 문자열이 제한할 숫자 길이를 초과하면 문자열을 해당 길이만큼 자르고, "..." 을 뒤에 덧붙여 반환합니다.
- 제한할 숫자 길이 이하인 경우는 전달받았던 문자열을 그대로 반환합니다!
- 패키지 상품 제목이나 설명이 너무 길어서 간추려야 할 경우 사용하실 수 있을것같은데요, 혹시 사용되는 컴포넌트가 없다면 추후 PR에서 삭제하겠습니다... 
- next.config.js 내 image 도메인 부분 구조 수정했습니다!
- 기존 테스트용 URL 주소 포함되어 있던 부분 수정했습니다.
- handler.ts 파일 …

Feat: 200_광고구좌페이지 퍼블리싱

---

src/app/_component/common/atom/LikeButton.tsx

- 진짜 혹시 모를 존재하지 않는 패키지에서 좋아요 요청 보냈을 때 모달창이 뜨고 메인페이지로 이동되도록 추가하였습니다.

Fix: 좋아요 존재하지 않는 패키지 핸들링 추가

---

src/app/(non-navbar)/theme/[id]/_component/ThemeDetail.tsx

v1/themes/{id} API 응답부 변경되면서 레이아웃 깨지던 부분 수정했습니다!
이전 응답 구조로는 각 패키지가 아래처럼 구성되어있어서 모든 패키지들에 한 가격만 보여줄 수밖에 없었는데, 변경되면서 각 패키지의 가격을 제대로 보여줄 수 있게 되었어요!
베스트 테마에서 호출하는 `/v1/packages/top-purchases(가장 많이 구매한 패키지 목록)` API는 구조 변경이 없어서 영향을 받지 않았습니다. 
수정 이전 API 구조
```
{
description: string;
imageUrl: string;
minPrice: number;
name: string;
packages: [
{
imageUrl: string;
packageId: number;
title: string;
transportation: string;
}, ...
]
themeId: string;
}
```
수정 이후 API 응답 데이터 구조
```
"code": 200,
"data": [
{
"themeId": 3,
"name": "자연경관",
"description": "숨이 탁 트이는 스트레스 zero 자연 힐링 여행 모음전",
"minPrice": 11990000,
"imageUrl": "https://i.postimg.cc/bNdXfwmm/nature.jpg",
"packages": [
{
"packageId": 24081310157,
"imageUrl": "https://tourimage.interpark.com/product/tour/00161/A30/1000/A3019433_5_070.jpg", …
```

feat: 테마페이지 API 변경 대응 개발

---

src/app/(non-navbar)/advertisement/[id]/_component/AdvertisementDetail.tsx
src/app/(non-navbar)/theme/[id]/_component/ThemeDetail.tsx

- 광고구좌 페이지 내 이미지 픽셀 설정함으로 인해 모바일과 웹뷰 사이 ( 376 ~ 499px )에서 레이아웃이 깨지는 문제가 있어 width값을 100%로 주는 식으로 수정했습니다.
- 테마 페이지 로딩 스피너 적용했습니다.
X
X

Refactor: 이미지 비율 처리 / 테마페이지 로딩스피너 적용
